spring:
#    开启消息跟踪
  rabbitmq:
    host: 134.175.5.236
    port: 5672
#    默认密码  guest

  application:
    name: config
  cloud:
    bus:
      trace:
        enabled: true
    config:
      label: master
      server:
        git:
          uri: https://gitee.com/xiaozhangqing/config-repo
          #uri: https://github.com/niyingla/repo
          username: 1047984367@qq.com
          password: as1314520
          basedir: /work/springcloud-study/config/basedir
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# 刷新时，关闭安全验证
management:
  endpoints:
    web:
      exposure:
        include: "*"

#server:
#  port: 8888
